#!/bin/bash

# sysinfo_page - A script to produce a File Directory Template


# Template for Photo Log

YEAR=$(date +"%Y")
CREATED=$(date +"%m-%d-%Y")
FILE="($YEAR)_PHOTOS_Created($CREATED)"

cd ~/Pictures
mkdir $FILE
cd $FILE
mkdir Month_1
cd Month_1
mkdir Family Curiosities ImportantF
cd ..
mkdir Month_{2..12} && for i in Month_{2..12}; do cp -r Month_1/* "$i"; done

# Test: If there is a file ImportantF in the

cd Month_7
if [ -d ImportantF ]; then
  echo "Directory completed"
else
  echo "Template failed"
fi
