#!/bin/bash

# sysinfo_page - A script to produce a File Directory Template


# Template for Photo Log

YEAR=$(date +"%Y")
CREATED=$(date +"%m-%d-%Y")
FILE= $YEAR_PHOTOS_$CREATED

cd ~/Pictures
mkdir $FILE
cd $FILE
mkdir Month_{1..12}
cd ~/$FILE/Month_1
mkdir {Family, Curiosities, ImportantF}
cp {Family, Curiosities, ImportantF} Month_{2..12}

# Test: If there is a file ImportantF in the
  direction ~/Pictures/$YEAR_PHOTOS_$CREATED/Month_7/

if ~/Pictures/$FILE/Month_7/
elif [open ImportantF = true]
  echo "Directory completed"
else
  echo "Template failed"
fi
